name: Deploy to Server via FTP

on:
  push:
    branches:
      - main # Agar aapki branch ka naam 'master' hai, toh ise 'master' kar dein.

jobs:
  web-deploy:
    name: 🎉 Deploy to FTP
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files to server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/ # Isko apne server ke hisaab se change kar lein (jaise / agar root me dalna hai)
